module.exports = {
  minRelaxFactor : 0.20,
  enableLookahead  : true,
  lookaheadSample  : 25,
  lookaheadMinPool : 15,
  deterministic : false,
  treatMissingScoreAs: 0,
  womenType  : "Žene",
  menType    : "Muškarci",
  unisexType : "Unisex",
  girlsType  : "Djevojčice",
  boysType   : "Dječaci",
  babyType   : "Bebe",
  pageSize          : 24,
  womenAdultsPerPage: 9,
  menAdultsPerPage  : 9,
  girlsPerPage      : 2,
  boysPerPage       : 2,
  babiesPerPage     : 2,
  femaleAccessoriesPerPage : 0,
  maleAccessoriesPerPage   : 0,
  banTopN              : 24,
  bannedCategoriesTopN : ["Setovi", "Potkošulje"],
  sprinklerScoreValue: -1,
  accessoryCategories: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Čarape","Pidžame","Kape","Donji veš","Veš","Peškiri",
  ],
  accessoryCategoryOrder: [],
  sprinklerCategoryOrder: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Pidžame","Peškiri","Čarape","Donji veš","Veš","Kape",
  ],
  maxSameTypeRun    : 3,
  maxSameCategoryRun: 4,
  scoreWeightCategory : 65,
  scoreWeightVariants : 25,
  scoreWeightInventory: 10,
  variantPercentile   : 95,
  inventoryPercentile : 95,
  categoryScores: {
    "Jakne"      : { Cold: 10, Mild: 6, Warm: 2,  Hot: 1  },
    "Dukserice"  : { Cold: 9,  Mild: 6, Warm: 2,  Hot: 1  },
    "Džemperi"   : { Cold: 10, Mild: 5, Warm: 1,  Hot: 1  },
    "Košulje"    : { Cold: 6,  Mild: 8, Warm: 7,  Hot: 6  },
    "Majice"     : { Cold: 3,  Mild: 7, Warm: 10, Hot: 10 },
    "Polo majice": { Cold: 3,  Mild: 7, Warm: 10, Hot: 10 },
    "Trenerke"   : { Cold: 8,  Mild: 6, Warm: 3,  Hot: 2  },
    "Šorcevi"    : { Cold: 1,  Mild: 5, Warm: 10, Hot: 10 },
    "Torbe"      : { Cold: 7,  Mild: 7, Warm: 8,  Hot: 8  },
  },
};
