module.exports = {
  penaltySameCategory    : 14,
  penaltySameColor       : 8,
  penaltySameType        : 4,
  penaltyInLast2Category : 5,
  penaltyInLast2Color    : 3,
  penaltyInLast2Type     : 1.5,
  penaltyInLast3Category : 1.5,
  penaltyInLast3Color    : 1,
  penaltyInLast3Type     : 0.5,
  penaltyInLast4Category : 1.0,
  penaltyInLast4Color    : 0.5,
  penaltyInLast4Type     : 0.3,
  penaltyInLast5Category : 0.5,
  penaltyInLast5Color    : 0.3,
  penaltyInLast5Type     : 0.2,
  relaxStep      : 0.80,
  minRelaxFactor : 0.20,
  enableLookahead  : true,
  lookaheadSample  : 25,
  lookaheadMinPool : 15,
  jitter        : 0.25,
  deterministic : false,
  treatMissingScoreAs: 0,
  womenType  : "Žene",
  menType    : "Muškarci",
  unisexType : "Unisex",
  girlsType  : "Djevojčice",
  boysType   : "Dječaci",
  babyType   : "Bebe",
  pageSize          : 24,
  womenAdultsPerPage: 9,
  menAdultsPerPage  : 9,
  girlsPerPage      : 2,
  boysPerPage       : 2,
  babiesPerPage     : 2,
  firstGender       : "auto",
  banTopN              : 24,
  bannedCategoriesTopN : ["Setovi", "Potkošulje"],
  sprinklerScoreValue: -1,
  accessoryCategories: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Čarape","Pidžame","Kape","Donji veš","Veš","Peškiri",
  ],
  sprinklerCategoryOrder: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Pidžame","Peškiri","Čarape","Donji veš","Veš","Kape",
  ],
  maxSameTypeRun    : 3,
  maxSameCategoryRun: 4,
  scoreWeightCategory : 0.65,
  scoreWeightVariants : 0.25,
  scoreWeightInventory: 0.10,
  categoryScores: {
    "Jakne"      : { zima: 10, proljece: 6, ljeto: 2,  jesen: 8 },
    "Dukserice"  : { zima: 9,  proljece: 6, ljeto: 2,  jesen: 8 },
    "Džemperi"   : { zima: 10, proljece: 5, ljeto: 1,  jesen: 9 },
    "Košulje"    : { zima: 6,  proljece: 8, ljeto: 7,  jesen: 7 },
    "Majice"     : { zima: 3,  proljece: 7, ljeto: 10, jesen: 6 },
    "Polo majice": { zima: 3,  proljece: 7, ljeto: 10, jesen: 6 },
    "Trenerke"   : { zima: 8,  proljece: 6, ljeto: 3,  jesen: 7 },
    "Šorcevi"    : { zima: 1,  proljece: 5, ljeto: 10, jesen: 3 },
    "Torbe"      : { zima: 7,  proljece: 7, ljeto: 8,  jesen: 7 },
  },
};
