module.exports = {
  penaltySameCategory    : 14,
  penaltySameColor       : 8,
  penaltySameType        : 4,
  penaltyInLast2Category : 5,
  penaltyInLast2Color    : 3,
  penaltyInLast2Type     : 1.5,
  penaltyInLast3Category : 1.5,
  penaltyInLast3Color    : 1,
  penaltyInLast3Type     : 0.5,
  penaltyInLast4Category : 1.0,
  penaltyInLast4Color    : 0.5,
  penaltyInLast4Type     : 0.3,
  penaltyInLast5Category : 0.5,
  penaltyInLast5Color    : 0.3,
  penaltyInLast5Type     : 0.2,
  relaxStep      : 0.80,
  minRelaxFactor : 0.20,
  enableLookahead  : true,
  lookaheadSample  : 25,
  lookaheadMinPool : 15,
  jitter        : 0.25,
  deterministic : false,
  treatMissingScoreAs: 0,
  womenType  : "Žene",
  menType    : "Muškarci",
  unisexType : "Unisex",
  girlsType  : "Djevojčice",
  boysType   : "Dječaci",
  babyType   : "Bebe",
  pageSize          : 24,
  womenAdultsPerPage: 9,
  menAdultsPerPage  : 9,
  girlsPerPage      : 2,
  boysPerPage       : 2,
  babiesPerPage     : 2,
  femaleAccessoriesPerPage : 0,
  maleAccessoriesPerPage   : 0,
  firstGender       : "auto",
  banTopN              : 24,
  bannedCategoriesTopN : ["Setovi", "Potkošulje"],
  sprinklerScoreValue: -1,
  accessoryCategories: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Čarape","Pidžame","Kape","Donji veš","Veš","Peškiri",
  ],
  sprinklerCategoryOrder: [
    "Torbe","Ruksaci","Novčanici","Kaiševi","Neseseri",
    "Manžetne","Pidžame","Peškiri","Čarape","Donji veš","Veš","Kape",
  ],
  maxSameTypeRun    : 3,
  maxSameCategoryRun: 4,
  scoreWeightCategory : 0.65,
  scoreWeightVariants : 0.25,
  scoreWeightInventory: 0.10,
  categoryScores: {
    "Jakne"      : { Cold: 10, Mild: 6, Warm: 2,  Hot: 1  },
    "Dukserice"  : { Cold: 9,  Mild: 6, Warm: 2,  Hot: 1  },
    "Džemperi"   : { Cold: 10, Mild: 5, Warm: 1,  Hot: 1  },
    "Košulje"    : { Cold: 6,  Mild: 8, Warm: 7,  Hot: 6  },
    "Majice"     : { Cold: 3,  Mild: 7, Warm: 10, Hot: 10 },
    "Polo majice": { Cold: 3,  Mild: 7, Warm: 10, Hot: 10 },
    "Trenerke"   : { Cold: 8,  Mild: 6, Warm: 3,  Hot: 2  },
    "Šorcevi"    : { Cold: 1,  Mild: 5, Warm: 10, Hot: 10 },
    "Torbe"      : { Cold: 7,  Mild: 7, Warm: 8,  Hot: 8  },
  },
};
